### PR TITLE
[enhancement] Added a crontab file #15

### LINKED ISSUE #15: Add empty crontab file
An empty crontab file will allow crond to start at boot and be reloaded in case OpenWISP supplies any update to the crontab.

### PR DESCRIPTION
**Pull request by EdgeKing810**
Added a crontab file. I feel like there's something more that needs to be done. If there is, please let me know.

Closes #15

### CODE REVIEW

**Review by nemesifier — CHANGES_REQUESTED** [review]
Yes it's just that but the file should go in: `files/etc/crontabs/root`, that way it will be included by default in the generated firmware image in the right location.

**Comment by EdgeKing810** [comment]
Okay... fixed that...

**Review by nemesifier — CHANGES_REQUESTED** [review]
@EdgeKing810 I wrote `files/etc/crontabs/root`, you put the file to `files/etc/crontabs/root/crontab`

**Comment by ppabcd** [comment]
create file `root` in `files/etc/crontabs/` directory @EdgeKing810

**Comment by ppabcd** [comment]
don't forget to squash commit ;)

**Comment by EdgeKing810** [comment]
Sorry! Didn't know the file was to be named root 😂😂😂.
I tend to assume that the path you tell me is just folders... 

Closes #15

**Review by nemesifier — CHANGES_REQUESTED** [review]
@EdgeKing810 still not right!

Path should be `files/etc/crontabs/root` and the commit message should be clean, just use `--amend`.

**Comment by EdgeKing810** [comment]
Sorry about the issues...
The next time I will be more careful when squashing my commits and will do it only when everything is fine.

**Review by nemesifier — APPROVED** [review]

**Pull request merged**
