### PR TITLE
use python's crypt function

### PR DESCRIPTION
**Pull request by pedro-nonfree**
I don't know what do you think about getting rid of one dependency (whois / mkpasswd) and using python itself.

I did not test the code so I don't know if it's working.

### CODE REVIEW

**Comment by pedro-nonfree** [comment]
If you care about salt randomness: https://gist.github.com/geekpete/7329085

**Review by nemesifier — COMMENTED** [review]
@pedro-nonfree thanks for taking the time to contribute, I have one question, what's the advantage of this approach?

**Comment by pedro-nonfree** [comment]
@nemesisdesign not much. you get rid of one strange dependency, but then that line looks more complex to read. And then is more complex to decide for python2 or python3 syntax.

You can close this pull request to have documented an alternate method

**Comment by nemesifier** [comment]
I think this part is working fine as of now, thank you for contributing to the discussion.

**Pull request closed without merging**
